DoctaDelivery/Controllers/PublicacionController.cs
using DoctaDelivery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctaDelivery.Controllers
{
    public class PublicacionController : Controller
    {
        //
        // GET: /Publicacion/
        private DoctaDBDataContext db = new DoctaDBDataContext();

        public ActionResult Index(int id_publicacion)
        {
            if (Request.IsAuthenticated)
            {
                String log = User.Identity.Name;
                var logeado = from l in db.Usuarios
                              where l.usuario1 == log
                              select l;

                var logeado2 = from l in db.Negocios
                               where l.usuario1 == log
                               select l;
                ViewBag.logear = logeado.ToArray();
                ViewBag.logear2 = logeado2.ToArray();

            }

            var publicacion = from p in db.Publicacions
                              where p.id_publicacion == id_publicacion
                              select p;

            ViewBag.publicaciones = publicacion.ToArray();
            var publi =  publicacion.ToArray();

            var foto = from f in db.Fotos
                       where f.id_publicacion == id_publicacion && f.borrado==0
                       select f;

            ViewBag.fotos = foto.ToArray();

            var producto = from r in db.Productos
                            where r.id_negocio == publi[0].id_negocio
                            select r;
            ViewBag.productos = producto.ToArray();

            var tipo = from r in db.Tipo_productos
                           select r;

            ViewBag.tipos = tipo.ToArray();

            return View();
        }

        [HttpPost]
        public ActionResult Editar(int tipo , int id_negocio,int id_publicacion)
        {
            var buscar = from b in db.Productos
                         where b.id_tipo_producto == tipo && b.id_negocio == id_negocio
                         select b;
            ViewBag.Seleccionados = buscar.ToArray();

            return RedirectToAction("Index", new { id_publicacion = id_publicacion });
        }
    }
}

DoctaDelivery/Views/Publicacion/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
    <div class="col-sm-10 col-md-10 col-lg-10">
        <div class="row" style="margin-top:1cm;">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="width:28cm;height:10cm;">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="item active" style="width:28cm;height:10cm;">
                        <img src="~/Imagen/@ViewBag.fotos[0].nombre" class="img-responsive">
                        <div class="carousel-caption">
                        </div>
                    </div>
                    <div class="item" style="width:28cm;height:10cm;">
                        <img src="~/Imagen/@ViewBag.fotos[1].nombre" class="img-responsive">
                        <div class="carousel-caption">
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Anterior</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Siguiente</span>
                </a>
            </div>
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1"></div>
        <div class="row">
            <div class="col-sm-10 col-md-10 col-lg-10">
                <div class="row cuerpo">
                    <br />
                    <hr />
                    <p><h4>@ViewBag.publicaciones[0].descripcion</h4></p>
                    <hr />
                    <br />
                    <h2 class="text-center">¿Que Desea Comer?</h2>
                    <div class="row">
                    <form action=@Url.Action("Editar", "Publicacion") method="post">
                        <input type="hidden" value="@ViewBag.productos[0].id_negocio" name="id_negocio" />
                        <input type="hidden" value="@ViewBag.publicaciones[0].id_publicacion" name="id_publicacion" />
                        <select class="form-control" name="tipo">
                            <option value="0">Seleccionar</option>
                            @foreach (var tipo in @ViewBag.tipos)
                            {
                                <option value="@tipo.id_tipo_producto">@tipo.nombre</option>
                            }
                        </select>
                        <button type="submit" class="btn btn-primary">Buscar</button>
                     </form>
 
                    </div>
                </div>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2"></div>
        </div>
    </div>
</div>