DoctaDelivery/Controllers/EditarProductoController.cs
using DoctaDelivery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctaDelivery.Controllers
{
    public class EditarProductoController : Controller
    {
        //
        // GET: /EditarProducto/
        private DoctaDBDataContext db = new DoctaDBDataContext();

        public ActionResult Index(int idNegocio )
        {

                if (Request.IsAuthenticated)
                {
                    String log = User.Identity.Name;
                    var logeado = from l in db.Usuarios
                                  where l.usuario1 == log
                                  select l;

                    var logeado2 = from l in db.Negocios
                                   where l.usuario1 == log
                                   select l;
                    ViewBag.logear = logeado.ToArray();
                    ViewBag.logear2 = logeado2.ToArray();

                }

                var prod = from p in db.Productos
                           where p.id_negocio == idNegocio && p.borrado==0
                           orderby p.Tipo_producto.nombre, p.nombre
                           select p;

                var publicacion = from p in db.Publicacions
                                  where p.id_negocio==idNegocio
                                  select p;

                ViewBag.publicaciones = publicacion.ToArray();


                ViewBag.productos = prod.ToArray();
                return View();
 

        }

        public ActionResult Editar(int id_producto,int id_negocio,Producto p,int tipo)
        {
            var producto = from a in db.Productos
                           where a.id_producto == id_producto
                           select a;

            var b = producto.ToArray();
            b[0].nombre = p.nombre;
            b[0].descripcion = p.descripcion;
            b[0].id_tipo_producto = tipo;
            b[0].precio = p.precio;
            b[0].tiempo = p.tiempo;
            b[0].coins = p.coins;
            db.SubmitChanges();
            return RedirectToAction("Index", new {idNegocio=id_negocio});
        }

        public ActionResult Eliminar(int id_producto, int id_negocio)
        {
            var producto = from a in db.Productos
                           where a.id_producto == id_producto
                           select a;
            var b = producto.ToArray();
            b[0].borrado = 1;
            db.SubmitChanges();
            return RedirectToAction("Index", new { idNegocio = id_negocio });
        }


    }
}

DoctaDelivery/Controllers/RegistrarProductoController.cs
using DoctaDelivery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctaDelivery.Controllers
{
    public class RegistrarProductoController : Controller
    {
        private DoctaDBDataContext db = new DoctaDBDataContext();

        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                String log = User.Identity.Name;
                var logeado = from l in db.Usuarios
                              where l.usuario1 == log
                              select l;

                var logeado2 = from l in db.Negocios
                               where l.usuario1 == log
                               select l;
                ViewBag.logear = logeado.ToArray();
                ViewBag.logear2 = logeado2.ToArray();

            }



            var tipoProd = from t in db.Tipo_productos
                           select t;
            ViewBag.TiposProductos = tipoProd.ToArray();
            return View();
        }

        public ActionResult CargarProducto(Producto p,int id_negocio)
        {
            p.id_negocio = id_negocio;
            p.borrado = 0;
            db.Productos.InsertOnSubmit(p);
            db.SubmitChanges();
            TempData["Producto"] = "Producto registrado con Exito !";
            return RedirectToAction("Index");
        }

    }
}

DoctaDelivery/Controllers/RegistrarPublicacionController.cs
using DoctaDelivery.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctaDelivery.Controllers
{
    public class RegistrarPublicacionController : Controller
    {
        private DoctaDBDataContext db = new DoctaDBDataContext();

        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                String log = User.Identity.Name;
                var logeado = from l in db.Usuarios
                              where l.usuario1 == log
                              select l;

                var logeado2 = from l in db.Negocios
                               where l.usuario1 == log
                               select l;
                ViewBag.logear = logeado.ToArray();
                ViewBag.logear2 = logeado2.ToArray();

            }

            var tipoProd = from t in db.Tipo_productos
                           select t;
            ViewBag.TiposProductos = tipoProd.ToArray();
            return View();
        }

        public ActionResult CrearPubli(Publicacion p,int id_negocio,string nombre,Foto f) 
        {
            var valid = from v in db.Publicacions
                        where v.id_negocio == id_negocio
                        select v;
            int validacion = valid.ToArray().Length;

            if (validacion == 0)
            {
                if (System.Web.HttpContext.Current.Request.Files != null)
                {
                    for (int i = 0; i < System.Web.HttpContext.Current.Request.Files.Keys.Count; i++)
                    {
                        HttpPostedFile file = System.Web.HttpContext.Current.Request.Files[i];
                        if (file != null && file.ContentLength > 0)
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            var path = Path.Combine(Server.MapPath("~/Imagen"), fileName);
                            file.SaveAs(path);
                            nombre = fileName;
                        }
                    }
                }
                
                p.id_negocio = id_negocio;
                p.valoracion = "0";
                db.Publicacions.InsertOnSubmit(p);
                db.SubmitChanges();
                f.id_publicacion = p.id_publicacion;
                f.nombre = nombre;
                f.borrado = 0;
                db.Fotos.InsertOnSubmit(f);
                db.SubmitChanges();
                TempData["Publicacion"]="Publicacion creada con Exito !";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Publicacion"] = "Ya tienes una publicacion creada.";
                return RedirectToAction("Index");
            }
        }

    }
}

DoctaDelivery/Views/EditarProducto/EditarProd.cshtml
<script type="text/javascript" src="~/Scripts/editarprod.js"></script>

DoctaDelivery/Views/EditarProducto/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ int c = -1;}
<div class="row">
    <div class="col-sm-4 col-md-2 col-lg-2">
        <div class="row">
            <div class="col-sm-8 col-md-8 col-lg-8 cuerpo">
                <h4 class="text-center">Menu</h4>
                <hr />
                <h6>Publicacion</h6>
                <div style="margin-top:4px;">
                    <a href="@Url.Action("Index", "RegistrarPublicacion", new { idNegocio = @ViewBag.logear2[0].id_negocio })"> cargar</a>
                </div>
                <div style="margin-top:4px;">
                    <a href="@Url.Action("Index", "EditarPublicacion", new { idNegocio = @ViewBag.logear2[0].id_negocio })">editar</a>
                </div>
                <div style="margin-top:4px;">
                    <a href=""> ver</a>
                    <hr />
                    <h6>Producto</h6>
                </div>
                <div style="margin-top:4px;">
                    <a href="@Url.Action("Index", "RegistrarProducto", new { idNegocio = @ViewBag.logear2[0].id_negocio })">cargar</a>
                </div>
                <div style="margin-top:4px;">
                    <a href="@Url.Action("Index", "EditarProducto", new {idNegocio=@ViewBag.logear2[0].id_negocio })">ver</a>
                </div>
                <hr />
                <br />
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4"></div>
        </div>
    </div>
    <div class="col-sm-7 col-md-9 col-lg-9 cuerpo">
        <h2 class="text-center">Productos</h2>
       <table class="table table-bordered" style="margin-top:1cm;">
           <tr>
               <th>Tipo Producto</th>
               <th>Nombre</th>
               <th>Descripcion</th>
               <th>Precio</th>
               <th>Tiempo</th>
               <th>Coins</th>
               <th>Accion</th>
           </tr>
 
           @foreach (var producto in ViewBag.productos)
           {
               c++;
               <tr>
                   <th hidden name="i@(c)">@producto.id_producto</th>
                   <th name="t@(c)">@producto.Tipo_producto.nombre</th>
                   <th name="n@(c)">@producto.nombre</th>
                   <th name="d@(c)">@producto.descripcion</th>
                   <th name="p@(c)">$@Convert.ToInt32(producto.precio)</th>
                   <th name="ti@(c)">@producto.tiempo .min</th>
                   <th name="c@(c)">@producto.coins</th>
                   <th>
                       <a role="button" class="btn btn-xs btn-primary" name="modifProd" id="@c">Modificar</a><a role="button" class="btn btn-xs btn-danger" style="margin-top:5px;" href="@Url.Action("Eliminar", "EditarProducto", new { id_negocio = @ViewBag.logear2[0].id_negocio,id_producto=@producto.id_producto })">Eliminar.</a></th>
               </tr>
           }
       </table>
    </div>
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
</div>

@section scripts{
    @RenderPage("~/Views/EditarProducto/EditarProd.cshtml")
}

DoctaDelivery/Views/EditarProducto/ModalEditar.cshtml
@model DoctaDelivery.Models.Producto


<div class="modal fade" tabindex="-1" role="dialog" id="modalProd">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Editar</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Editar", "EditarProducto", FormMethod.Post))
                {
                    if (Request.IsAuthenticated)
                    {
                        <div>
                            <input type="hidden" value="@ViewBag.logear2[0].id_negocio " name="id_negocio" />
                        </div>

                    }
                    <div>
                        <input type="hidden"  name="id_producto" />
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">Producto:</label>
                        <div class="col-sm-9">
                            <select class="form-control" id="select" name="tipo">
                                <option value="1">Lomito</option>
                                <option value="2">Empanada</option>
                                <option value="3">Pizza</option>
                                <option value="4">Hamburguesa</option>
                                <option value="5">Pollo</option>
                                <option value="6">Tarta</option>
                                <option value="7">Menu Diario</option>
                            </select>
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                    <div class="form-group">
                        <label class="control-label col-sm-3">Nombre:</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.nombre, new { @class = "form-control", type = "text", placeholder = "Nombre", required = "required", maxlength = "25"})
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                    <div class="form-group">
                        <label class="control-label col-sm-3">Descripcion:</label>
                        <div class="col-sm-9">
                            @Html.TextAreaFor(x => x.descripcion, new { @class = "form-control", rows = "4", cols = "6", placeholder = "Ingredientes", required = "required", maxlength = "400" })
                        </div>  
                    </div>                  
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <div class="form-group">
                        <label class="control-label col-sm-3">Precio:</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.precio, new { @class = "form-control", type = "number", required = "required" })
                        </div>
                    </div>
                    <br />
                    <br />
                    <div class="form-group">
                        <label class="control-label col-sm-3">Tiempo Estimado:</label>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(x => x.tiempo, new { @class = "form-control", type = "number", required = "required" })
                            <p class="help-block">En minutos</p>
                        </div>
                        <label>min.</label>
                    </div>
                    <br />
                    <br />
                    <div class="form-group">
                        <label class="control-label col-sm-3">Coins:</label>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(x => x.coins, new { @class = "form-control", type = "number", required = "required" })
                        </div>
                    </div>
                    <br />
                    <hr />
                    <br />
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    </div>
                }
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->